# Generated by Django 6.0.4 on 2026-04-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=20)),
                ('flight_source', models.CharField(max_length=30)),
                ('flight_dest', models.CharField(max_length=30)),
                ('flight_timming', models.FloatField()),
                ('ticket_price', models.FloatField()),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=20)),
                ('flight_source', models.CharField(max_length=30)),
                ('flight_dest', models.CharField(max_length=30)),
                ('flight_timming', models.FloatField()),
                ('ticket_price', models.FloatField()),
                ('date', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_age', models.IntegerField()),
                ('user_phone', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('seat_class', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='flight',
        ),
    ]
