# Generated by Django 6.0.4 on 2026-04-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_flights_user_tickets_delete_flight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='flights',
            new_name='flight',
        ),
    ]
