# Generated by Django 6.0.4 on 2026-04-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_flights_flight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='flight',
            new_name='Flights',
        ),
    ]
